// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKraCmrQY6VQs7kWv5PIv_u5zJh9IBJss',
    appId: '1:586900251454:web:fbfe6de7e65144a6e5826f',
    messagingSenderId: '586900251454',
    projectId: 'blog-app-5cb3f',
    authDomain: 'blog-app-5cb3f.firebaseapp.com',
    storageBucket: 'blog-app-5cb3f.appspot.com',
    measurementId: 'G-EXSTCM7KT2',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAPgsT36kWXavS4omGaKTA3f2JsU3kbc',
    appId: '1:586900251454:android:9c572b80af6edf73e5826f',
    messagingSenderId: '586900251454',
    projectId: 'blog-app-5cb3f',
    storageBucket: 'blog-app-5cb3f.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlju_haWJ5cF2UETIpYy4db8FACVVG5jw',
    appId: '1:586900251454:ios:04ec0e623625b645e5826f',
    messagingSenderId: '586900251454',
    projectId: 'blog-app-5cb3f',
    storageBucket: 'blog-app-5cb3f.appspot.com',
    iosBundleId: 'com.mbr.blogApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlju_haWJ5cF2UETIpYy4db8FACVVG5jw',
    appId: '1:586900251454:ios:04ec0e623625b645e5826f',
    messagingSenderId: '586900251454',
    projectId: 'blog-app-5cb3f',
    storageBucket: 'blog-app-5cb3f.appspot.com',
    iosBundleId: 'com.mbr.blogApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKraCmrQY6VQs7kWv5PIv_u5zJh9IBJss',
    appId: '1:586900251454:web:d2e414a8745cd43ae5826f',
    messagingSenderId: '586900251454',
    projectId: 'blog-app-5cb3f',
    authDomain: 'blog-app-5cb3f.firebaseapp.com',
    storageBucket: 'blog-app-5cb3f.appspot.com',
    measurementId: 'G-TC49V5ZBQK',
  );
}
